### ISSUE TITLE
proxys and locked tokens

### ISSUE THREAD

**Issue by baum1810** [dropout1337/Discord-Token-Creator#11]
i have multible problems so first if i let it run with proxys (testet multibele that i checked http and socks4) it just always says conecction error

second if i let it run without proxys and like over a vpn it just generates locked accounts

and 3rd i did let it run without proxys for like something around 2 min and it generated 4 locked tokens but when i looked on the captcha side it used something around 80 captchas
 would be nice if someone helps me to solve the error

**Comment by cChimney** [comment]
It doesn't do unlocked tokens L

**Comment by baum1810** [comment]
then what is the point in using it i mean locked tokens cant be used lol

**Comment by dropout1337** [comment]
member botting for now.
