### ISSUE TITLE
any recommended proxy providers

### ISSUE THREAD

**Issue by dankrainbow** [dropout1337/Discord-Token-Creator#13]
yeah what it says above - any proxy providers that work decently well on discord?

**Comment by IIIIIIIIIIIIIII-CRYPT** [comment]
https://github.com/iw4p/proxy-scraper
use this tool to scrape them and check them with timeout time as 5 seconde, you will have nice proxy

**Comment by dankrainbow** [comment]
tried that, they are really bad

**Comment by dankrainbow** [comment]
thanks for the help imma close the issue
