### ISSUE TITLE
main.py:158: DeprecationWarning: There is no current event loop   asyncio.get_event_loop().run_until_complete(client.start())

### ISSUE THREAD

**Issue by DeathGates** [dropout1337/Discord-Token-Creator#8]
main.py:158: DeprecationWarning: There is no current event loop
  asyncio.get_event_loop().run_until_complete(client.start())

**Comment by dropout1337** [comment]
google it, not my problem

**Comment by Weberowsky** [comment]
It is ur problem cuz it still doesnt work
